### ISSUE TITLE
tutorial wont multi deploy - cant resolve local hostname

### ISSUE THREAD

**Issue by stevemcghee** [ServiceWeaver/weaver#154]
this feels like an env variable problem, but its not clear which var or how to override.

when following the tutorial, i get to the `multi deploy` phase and i get this output when trying to hit the endpoint for the first time:

> S0313 11:24:35.338221 stderr  c17304c8           ] error initializing Service Weaver: error creating internal listener: listen tcp: lookup HOSTNAME.COMPANY.com: no such host

(hostname PII redacted) 

it seems like it is trying to resolve my FQDN, but should really just be using localhost or the loopback IP.

FWIW, single deploy is working fine:

```
hello listener available on 127.0.0.1:12345
╭───────────────────────────────────────────────────╮
│ app        : hello                                │
│ deployment : ddde8609-00e3-4074-a41c-60f6fa3e4275 │
╰───────────────────────────────────────────────────╯
```

```
curl "localhost:12345/hello?name=Weaver"
Hello, revaeW!
```

**Comment by rgrandl** [comment]
Thanks @stevemcghee . It's very likely we introduced a bug with one of our recent changes. We are working on a fix. Sorry about that.

**Comment by leocavalcante** [comment]
As a workaround for now, add you hostname to your `/etc/hosts`.
```
127.0.0.1 HOSTNAME.COMPANY.com
```

**Comment by mwhittaker** [comment]
Hi @stevemcghee, can you run the following program on your machine for me and tell what it prints out? I'm working on a fix right now, but want to see if what I think is wrong is actually what's wrong.

```go
package main

import (
	"fmt"
	"net"
	"os"
)

func main() {
	// Listen on localhost.
	_, err := net.Listen("tcp", "localhost:0")
	if err != nil {
		fmt.Printf("ERROR listening on localhost: %v\n", err)
	} else {
		fmt.Println("SUCCESS listening on localhost")
	}

	// Listen on $HOSTNAME.
	host, err := os.Hostname()
	if err != nil {
		fmt.Printf("ERROR getting hostname: %v\n", err)
		return
	}
	_, err = net.Listen("tcp", host+":0")
	if err != nil {
		fmt.Printf("ERROR listening on $HOSTNAME: %v\n", err)
	} else {
		fmt.Println("SUCCESS listening on $HOSTNAME")
	}
}
```

**Comment by stevemcghee** [comment]
> SUCCESS listening on localhost

(haven't edited `/etc/hosts` at this point)

**Comment by mwhittaker** [comment]
Thanks @stevemcghee! That's very helpful. I opened PR #156, which should address this issue.

**Comment by mwhittaker** [comment]
Hi @stevemcghee, I merged #156 which I think should fix your problem. If it doesn't, please re-open the issue!

**Comment by ttallskog** [comment]
Hi, I have the same problem and using @latest version doesn't resolve the problem. 

running the code you provided above returns this:

> SUCCESS listening on localhost
> ERROR listening on $HOSTNAME: listen tcp: lookup "machine name": no such host

Any ideas?

**Comment by mwhittaker** [comment]
@ttallskog, do you mind sharing what you did and what error message you got? I'll re-open this issue and help you debug.

**Comment by ttallskog** [comment]
@mwhittaker I was running the introduction `https://serviceweaver.dev/docs.html#step-by-step-tutorial` and failed when running command `weaver multi deploy` with the error:

hello % ~/go/bin/weaver multi deploy weaver.toml 
╭───────────────────────────────────────────────────╮
│ app        : hello                                │
│ deployment : a1668867-e51c-4bf0-a547-1c0598dd0fc2 │
╰───────────────────────────────────────────────────╯
S0321 14:15:29.033529 stderr  bf248e0a           ] error initializing Service Weaver: error creating internal listener: listen tcp: lookup _machine name_: no such host
S0321 14:15:29.034529 stderr  b196cfc8           ] error initializing Service Weaver: error creating internal listener: listen tcp: lookup _machine name_: no such host


After this I ran the code provided by you @mwhittaker with the result: 

SUCCESS listening on localhost
ERROR listening on $HOSTNAME: listen tcp: lookup _machine name_: no such host

do you need more information?

**Comment by mwhittaker** [comment]
Thanks @ttallskog! And what's the version of service weaver in your `go.mod` file?

**Comment by alvin1221** [comment]
> 

I guest `v0.1.5`, because I have also met the same issue.

**Comment by ttallskog** [comment]
Yes, it's version 0.1.5.

Den lör 25 mars 2023 16:27alvin1221 ***@***.***> skrev:

**Comment by kazshinohara** [comment]
same here.

**Comment by mwhittaker** [comment]
Hm, here's some things I would do to debug. First, delete the following directories. Note that doing so will delete any history of any Service Weaver apps you're running locally.

```console
rm -r ~/.local/share/serviceweaver/
rm -r /tmp/serviceweaver/
```

Next, make sure that the weaver tool *and* the compiled Service Weaver binary are at the latest version. If your application binary is at the latest version, but the `weaver multi deploy` command is stale, things will break. To do this, re-run the following command:

```
go install github.com/ServiceWeaver/weaver/cmd/weaver@latest
```

And in the `go.mod` file in your application, make sure you're using the latest version of Service Weaver. 

If the problem persists after all this, please let me know!

**Comment by rgrandl** [comment]
@stevemcghee, @ttallskog, @kazshinohara  is this still an issue for you?
